import Image from 'next/image'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import dataExample from '../services/data'

export default function Home({ data }) {
  const products = data.data.search.searchResult.itemStacks[0].items

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {products.map((product) => (

          <div key={product.id}>
            <h1>{product.name}</h1>
            <Image src={product.imageInfo.thumbnailUrl} alt={product.name} width={200} height={200} />
          </div>
        ))}
      </main>
    </div>
  )

}

export async function getServerSideProps() {
  const result = await fetch('http://localhost:3000/api/getData');
  const data = await result.json();
  return { props: { data } }
}