import Image from 'next/image'
import Head from 'next/head'
import { getSession, signOut } from 'next-auth/react'


export default function Profile({ session }) {

  return (
    <div className='container'>
      <Head>
        <title>Matketplace cool | profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        {
          <div className="main">
            <h1> Hi {session.user.name}</h1>
            <Image src={session.user.image} alt={session.user.name} width={100} height={100} />
          </div>
        }
        <button onClick={() => signOut()}>
          Sign out
        </button>
      </main>
    </div>
  )

}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: '/api/auth/signin',
        permanent: false,
      },
    }
  }

  return { props: { session } }
}