import Image from 'next/image'
import Head from 'next/head'
import { getSession, signOut } from 'next-auth/react'


export default function Profile({ session }) {

  return (
    <div className='main bg-gray-900 grid place-items-center h-screen'>
      <Head>
        <title>Matketplace cool | profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="name text-white text-2xl font-medium mt-4 ">
        {
          <>
            <h1 > Hola {session.user.name}</h1>
            <div class="profile mx-auto rounded-full py-2 w-16 ">
              <Image
                src={session.user.image}
                alt={session.user.name}
                width={300}
                height={300}
                className="inline w-full h-56 rounded-lg margin-auto"
              />
            </div>
          </>
        }
        <button
          onClick={() => signOut()}
          className="bg-gray-800 hover:bg-gray-700 text-white py-2 px-4 rounded text-lg"
        >
          Salir
        </button>
      </main>
    </div>
  )

}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: '/api/auth/signin',
        permanent: false,
      },
    }
  }

  return { props: { session } }
}